#!/bin/bash
# Instructions for domain privacy protection

echo "🔒 Domain Privacy Protection Setup"
echo "===================================="
echo ""
echo "PROBLEM: Domain WHOIS records show who bought the domain"
echo "SOLUTION: Enable WHOIS Privacy Protection"
echo ""
echo "OPTION 1: Use Cloudflare Domain Privacy (RECOMMENDED)"
echo "  - Cloudflare automatically hides your WHOIS information"
echo "  - Free with Cloudflare"
echo "  - Steps:"
echo "    1. Transfer domain to Cloudflare Registrar (or buy from Cloudflare)"
echo "    2. Privacy is automatically enabled"
echo "    3. WHOIS shows Cloudflare's info, not yours"
echo ""
echo "OPTION 2: Enable Privacy at Current Registrar"
echo "  - Most registrars offer 'WHOIS Privacy' or 'Domain Privacy'"
echo "  - Usually costs $5-15/year"
echo "  - Steps:"
echo "    1. Login to your domain registrar"
echo "    2. Find 'WHOIS Privacy' or 'Domain Privacy' option"
echo "    3. Enable it"
echo "    4. Your info will be replaced with privacy service info"
echo ""
echo "OPTION 3: Use Fake Information (Not Recommended)"
echo "  - Use fake name/address when registering"
echo "  - Use privacy-focused email service"
echo "  - Use PO Box or virtual address"
echo "  - ⚠️  May violate registrar terms of service"
echo ""
echo "CHECK YOUR CURRENT WHOIS:"
echo "  Run: whois gunduata.online"
echo "  If it shows your real name/email/address, enable privacy NOW"
echo ""
