#!/bin/bash
# Instructions for VPN/Proxy setup (manual steps required)

echo "🔐 VPN/Proxy Setup Instructions"
echo "=================================="
echo ""
echo "For maximum anonymity, use one of these options:"
echo ""
echo "OPTION 1: Use Cloudflare (Recommended - Free)"
echo "1. Sign up at https://www.cloudflare.com"
echo "2. Add domain: gunduata.online"
echo "3. Change nameservers to Cloudflare"
echo "4. Enable 'Proxy' (orange cloud)"
echo "5. Enable 'Always Use HTTPS'"
echo "6. Enable 'Under Attack Mode'"
echo ""
echo "OPTION 2: Use VPN Service"
echo "1. Subscribe to VPN service (NordVPN, ExpressVPN, etc.)"
echo "2. Install VPN on server"
echo "3. Route all traffic through VPN"
echo ""
echo "OPTION 3: Use Tor/Onion Service (Advanced)"
echo "1. Install Tor: apt-get install tor"
echo "2. Configure hidden service"
echo "3. Access via .onion address"
echo ""
echo "Current server IP will be hidden once proxy/VPN is configured."
